

HEAP SUMMARY:
    in use at exit: ... bytes in ... blocks
  total heap usage: ... allocs, ... frees, ... bytes allocated

For a detailed leak analysis, rerun with: --leak-check=full

For counts of detected and suppressed errors, rerun with: -v
ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Unaddressable byte(s) found during client check request
   at 0x........: test2 (addressable.c:50)
   by 0x........: main (addressable.c:127)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Invalid write of size 1
   at 0x........: test2 (addressable.c:53)
   by 0x........: main (addressable.c:127)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd


HEAP SUMMARY:
    in use at exit: ... bytes in ... blocks
  total heap usage: ... allocs, ... frees, ... bytes allocated

For a detailed leak analysis, rerun with: --leak-check=full

For counts of detected and suppressed errors, rerun with: -v
ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Uninitialised byte(s) found during client check request
   at 0x........: test5 (addressable.c:87)
   by 0x........: main (addressable.c:127)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd

Uninitialised byte(s) found during client check request
   at 0x........: test5 (addressable.c:93)
   by 0x........: main (addressable.c:127)
 Address 0x........ is not stack'd, malloc'd or (recently) free'd


HEAP SUMMARY:
    in use at exit: ... bytes in ... blocks
  total heap usage: ... allocs, ... frees, ... bytes allocated

For a detailed leak analysis, rerun with: --leak-check=full

For counts of detected and suppressed errors, rerun with: -v
Use --track-origins=yes to see where uninitialised values come from
ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)

HEAP SUMMARY:
    in use at exit: ... bytes in ... blocks
  total heap usage: ... allocs, ... frees, ... bytes allocated

For a detailed leak analysis, rerun with: --leak-check=full

For counts of detected and suppressed errors, rerun with: -v
ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
