/*
 * taintgrind.h
 *
 *  Created on: Jun 12, 2012
 *      Author: khilan
 */

#ifndef TAINTGRIND_H_
#define TAINTGRIND_H_

#include "valgrind.h"
#include <sys/syscall.h>

typedef enum {
	VG_USERREQ__TAINTGRIND_ENTERSANDBOX,
	VG_USERREQ__TAINTGRIND_EXITSANDBOX,
	VG_USERREQ__TAINTGRIND_FORKSANDBOX,
	VG_USERREQ__TAINTGRIND_SHAREDFD,
	VG_USERREQ__TAINTGRIND_SHAREDOPEN,
	VG_USERREQ__TAINTGRIND_SHAREDFILE,
	VG_USERREQ__TAINTGRIND_SHAREDVAR,
	VG_USERREQ__TAINTGRIND_UPDATESHAREDVAR,
	VG_USERREQ__TAINTGRIND_ALLOWSYSCALL
} Vg_TaintGrindClientRequest;

#define TNT_RUN_IN_SANDBOX(fncall) \
	{ \
		VALGRIND_DO_CLIENT_REQUEST_STMT(VG_USERREQ__TAINTGRIND_ENTERSANDBOX, 0, 0, 0, 0, 0); \
		fncall; \
		VALGRIND_DO_CLIENT_REQUEST_STMT(VG_USERREQ__TAINTGRIND_EXITSANDBOX, 0, 0, 0, 0, 0); \
	}

#define TNT_CREATE_SANDBOX() \
		VALGRIND_DO_CLIENT_REQUEST_STMT(VG_USERREQ__TAINTGRIND_FORKSANDBOX, 0, 0, 0, 0, 0)

#define TNT_SHARED_FILE_ONLY(file) \
		VALGRIND_DO_CLIENT_REQUEST_STMT(VG_USERREQ__TAINTGRIND_SHAREDFD, fileno(file), 0, 0, 0, 0)

#define TNT_SHARED_FD(fd,rhs) \
	{ \
		VALGRIND_DO_CLIENT_REQUEST_STMT(VG_USERREQ__TAINTGRIND_SHAREDOPEN, 0, 0, 0, 0, 0); \
		fd = rhs; \
		VALGRIND_DO_CLIENT_REQUEST_STMT(VG_USERREQ__TAINTGRIND_SHAREDFD, fd, 0, 0, 0, 0); \
	}

#define TNT_SHARED_FILE(file,rhs) \
	{ \
		VALGRIND_DO_CLIENT_REQUEST_STMT(VG_USERREQ__TAINTGRIND_SHAREDOPEN, 0, 0, 0, 0, 0); \
		file = rhs; \
		VALGRIND_DO_CLIENT_REQUEST_STMT(VG_USERREQ__TAINTGRIND_SHAREDFD, fileno(file), 0, 0, 0, 0); \
	}

#define TNT_LOCAL_FILE(file,rhs) \
	{ \
		VALGRIND_DO_CLIENT_REQUEST_STMT(VG_USERREQ__TAINTGRIND_SHAREDOPEN, 0, 0, 0, 0, 0); \
		file = rhs; \
	}

#define TNT_SHARED_VAR(var) \
		VALGRIND_DO_CLIENT_REQUEST_STMT(VG_USERREQ__TAINTGRIND_SHAREDVAR, #var, 0, 0, 0, 0)

#define TNT_UPDATE_SHARED_VAR(var,value) \
	{ \
		VALGRIND_DO_CLIENT_REQUEST_STMT(VG_USERREQ__TAINTGRIND_UPDATESHAREDVAR,#var,0,0,0,0); \
		var = value; \
	}

#define TNT_ALLOW_SYSCALL(syscallno) \
		VALGRIND_DO_CLIENT_REQUEST_STMT(VG_USERREQ__TAINTGRIND_ALLOWSYSCALL,syscallno,0,0,0,0); \

#endif /* TAINTGRIND_H_ */
